### ISSUE TITLE
As a consumer I want the render to display in correct format

### ISSUE THREAD

**Issue by sminke** [autorivalry/ar-render#24] opened 2016-01-18 17:04 UTC
(gray screen to match blue screen)

**Comment by sminke** [comment] 2016-01-18 17:05
@jordanskole

**Comment by jordanskole** [comment] 2016-01-18 21:48
Closing this issue because from my perspective it appears to be a duplicate of #20. If it isn't feel free to reopen it with more descriptive context. 

Also, FYI nitpicking, consumers (or anyone) doesn't really have a concept of "correct" or "incorrect."

**Closed as completed** 2016-01-18 21:49 UTC
