### ISSUE TITLE
In comparison specs, highlight (green) hero vehicle advantage attributes

### ISSUE THREAD

**Issue by motstuff** [autorivalry/ar-render#39] opened 2016-01-31 16:37 UTC
Make "pop" either with increased font size, or bold and lighten villain attribute

**Comment by jordanskole** [comment] 2016-01-31 16:41
Hey @motstuff, isn't this a duplicate of #21 ?

**Comment by motstuff** [comment] 2016-01-31 16:43
yes, sorry. I did a search by 'check' and 'mark' but not 'checkmark'  Please close as this is a duplicate

**Comment by jordanskole** [comment] 2016-01-31 16:44
Okay cool, just making sure. Fyi this should be live on production if you want to check it out. I'll come back to it when I finish the other Omni requests to see how it can be improved (via that page you sent in slack)

**Closed as completed by jordanskole** 2016-01-31 16:44 UTC
